# Generated by Django 3.2.25 on 2024-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], max_length=20)),
                ('port', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('image', models.FileField(default=True, null=True, upload_to='upload')),
            ],
        ),
    ]
